# Sensitive Configuration
# Copy .env.example to .env and fill in your values
ad_admin_password: "{{ lookup('env', 'AD_ADMIN_PASSWORD') }}"

# Cloud credentials (for extensions)
azure_client_id: "{{ lookup('env', 'AZURE_CLIENT_ID') }}"
azure_client_secret: "{{ lookup('env', 'AZURE_CLIENT_SECRET') }}"
azure_tenant_id: "{{ lookup('env', 'AZURE_TENANT_ID') }}"
azure_storage_account: "{{ lookup('env', 'AZURE_STORAGE_ACCOUNT') }}"

aws_access_key_id: "{{ lookup('env', 'AWS_ACCESS_KEY_ID') }}"
aws_secret_access_key: "{{ lookup('env', 'AWS_SECRET_ACCESS_KEY') }}"
aws_s3_bucket: "{{ lookup('env', 'AWS_S3_BUCKET') }}"