all:
  children:
    file_servers:
      hosts:
        file-server:
          ansible_host: 192.168.198.141 # 4GB RAM, 40GB disk RHEL 9
          ansible_user: simoda
          ansible_become_method: sudo
    backup_servers:
      hosts:
        backup-server:
          ansible_host: 192.168.198.12 # 2GB RAM, 60GB disk Ubuntu 22.04
          ansible_user: ubuntu
    clients:
      hosts:
        client-workstation:
          ansible_host: 192.168.198.143 # 2GB RAM, 20GB disk Ubuntu 22.04
          ansible_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
