all:
  children:
    file_servers:
      hosts:
        file-server:
          ansible_host: 192.168.198.20
          ansible_user: ubuntu
    backup_servers:
      hosts:
        backup-server:
          ansible_host: 192.168.198.21
          ansible_user: ubuntu
    clients:
      hosts:
        client-workstation:
          ansible_host: 192.168.198.22
          ansible_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'