all:
  children:
    file_servers:
      hosts:
        file-server:
          ansible_host: 192.168.198.132 # 4GB RAM, 40GB disk Ubuntu 22.04
          ansible_user: ubuntu
          file_server_ip: 192.168.198.132
    backup_servers:
      hosts:
        backup-server:
          ansible_host: 192.168.198.131 # 2GB RAM, 60GB disk Ubuntu 22.04
          ansible_user: ubuntu
    clients:
      hosts:
        client-workstation:
          ansible_host: 192.168.198.131 # 2GB RAM, 20GB disk Ubuntu 22.04
          ansible_user: ubuntu
  vars:
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_ssh_common_args: "-o StrictHostKeyChecking=no"
