---
- name: Update package cache
  apt:
    update_cache: yes
    cache_valid_time: 3600

- name: Install base packages
  apt:
    name:
      - curl
      - wget
      - vim
      - htop
      - ufw
      - chrony
    state: present

- name: Configure firewall
  ufw:
    rule: allow
    port: "{{ item }}"
  loop:
    - "22"
    - "445"
    - "2049"
  when: firewall_enabled

- name: Enable firewall
  ufw:
    state: enabled
  when: firewall_enabled

- name: Configure NTP
  systemd:
    name: chrony
    enabled: yes
    state: started