---
- name: Deploy Enterprise File Server Platform
  hosts: all
  become: yes
  roles:
    - common

- name: Configure File Server
  hosts: file_servers
  become: yes
  roles:
    - samba
    - nfs-server
    - monitoring

- name: Configure Backup Server
  hosts: backup_servers
  become: yes
  roles:
    - backup
    - monitoring

- name: Configure Client Workstation
  hosts: clients
  become: yes
  roles:
    - autofs